### ISSUE TITLE
Adjusting the output filenames depending on impl_params

### ISSUE THREAD

**Issue by jbueltemeier** [pystiche/papers#275]
There are currently scripts to create the images for the parameters from the reference implementation as well as for the paper. However, the file name is currently the same for both scripts. Therefore, I would suggest that similar to `johnson_et_al_2016`, the name is adjusted depending on `impl_params` so that the files are not overwritten when both variants are created.

Example: `gatys_ecker_betghe_2016`
Current: "_fig_2__d.jpg_"
New: "_fig_2__d.jpg_" if `impl_params` else "_fig_2__d__paper.jpg_"

This would affect the scripts of:
`gatys_ecker_betghe_2016`
`gatys_et_al_2017`
`li_wand_2016`

What do you think @pmeier ?

**Comment by pmeier** [comment]
SGTM, go for it!
