### ISSUE TITLE
Partially wrong num_batches in johnson_alahi_li_2016 training

### ISSUE THREAD

**Issue by jbueltemeier** [pystiche/papers#292]
Small question about [training.py](https://github.com/pystiche/papers/blob/main/replication/johnson_alahi_li_2016/training.py) in `johnson_alahi_li_2016`. The original authors have published hyperparameters for the different styles, which we also use in the replication. Among other things, the hyperparameter `num_batches` have to be adjusted. Doesn't `image_loader` in [`main(args)`](https://github.com/pystiche/papers/blob/c5e075231d58fa1556a47a50d851a72f21ded443/replication/johnson_alahi_li_2016/training.py#L87) therefore have to be created later with the adapted hyperparameters? Or am I missing something there?

Proposal change:
```python
def main(args):
    dataset = paper.dataset(args.dataset_dir, impl_params=args.impl_params)

    for style in args.style:
        style_image = read_style_image(
            args.images_source_dir, style, device=args.device
        )

        hyper_parameters = adapted_hyper_parameters(
            args.impl_params, args.instance_norm, style
        )
        content_image_loader = paper.image_loader(
            dataset,
            hyper_parameters=hyper_parameters,
            pin_memory=str(args.device).startswith("cuda"),
        )
...
```

**Comment by pmeier** [comment]
This also needs to be updated:

https://github.com/pystiche/papers/blob/c5e075231d58fa1556a47a50d851a72f21ded443/pystiche_papers/johnson_alahi_li_2016/_data.py#L227

**Comment by pmeier** [comment]
Makes sense, go for it!
